# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gburgyan/dev/VLife

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gburgyan/dev/VLife

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gburgyan/dev/VLife/CMakeFiles /Users/gburgyan/dev/VLife//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gburgyan/dev/VLife/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameOfLifeLib

# Build rule for target.
GameOfLifeLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeLib
.PHONY : GameOfLifeLib

# fast build rule for target.
GameOfLifeLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/build
.PHONY : GameOfLifeLib/fast

#=============================================================================
# Target rules for targets named GameOfLifeApp

# Build rule for target.
GameOfLifeApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeApp
.PHONY : GameOfLifeApp

# fast build rule for target.
GameOfLifeApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/build
.PHONY : GameOfLifeApp/fast

#=============================================================================
# Target rules for targets named GameOfLifeTests

# Build rule for target.
GameOfLifeTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeTests
.PHONY : GameOfLifeTests

# fast build rule for target.
GameOfLifeTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/build
.PHONY : GameOfLifeTests/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named VLifeBenchmark

# Build rule for target.
VLifeBenchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VLifeBenchmark
.PHONY : VLifeBenchmark

# fast build rule for target.
VLifeBenchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/build
.PHONY : VLifeBenchmark/fast

#=============================================================================
# Target rules for targets named run_benchmark

# Build rule for target.
run_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_benchmark
.PHONY : run_benchmark

# fast build rule for target.
run_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_benchmark.dir/build.make CMakeFiles/run_benchmark.dir/build
.PHONY : run_benchmark/fast

#=============================================================================
# Target rules for targets named run_benchmark_quick

# Build rule for target.
run_benchmark_quick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_benchmark_quick
.PHONY : run_benchmark_quick

# fast build rule for target.
run_benchmark_quick/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_benchmark_quick.dir/build.make CMakeFiles/run_benchmark_quick.dir/build
.PHONY : run_benchmark_quick/fast

#=============================================================================
# Target rules for targets named GameOfLifeLib_autogen_timestamp_deps

# Build rule for target.
GameOfLifeLib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeLib_autogen_timestamp_deps
.PHONY : GameOfLifeLib_autogen_timestamp_deps

# fast build rule for target.
GameOfLifeLib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib_autogen_timestamp_deps.dir/build.make CMakeFiles/GameOfLifeLib_autogen_timestamp_deps.dir/build
.PHONY : GameOfLifeLib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named GameOfLifeLib_autogen

# Build rule for target.
GameOfLifeLib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeLib_autogen
.PHONY : GameOfLifeLib_autogen

# fast build rule for target.
GameOfLifeLib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib_autogen.dir/build.make CMakeFiles/GameOfLifeLib_autogen.dir/build
.PHONY : GameOfLifeLib_autogen/fast

#=============================================================================
# Target rules for targets named GameOfLifeApp_autogen_timestamp_deps

# Build rule for target.
GameOfLifeApp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeApp_autogen_timestamp_deps
.PHONY : GameOfLifeApp_autogen_timestamp_deps

# fast build rule for target.
GameOfLifeApp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp_autogen_timestamp_deps.dir/build.make CMakeFiles/GameOfLifeApp_autogen_timestamp_deps.dir/build
.PHONY : GameOfLifeApp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named GameOfLifeApp_autogen

# Build rule for target.
GameOfLifeApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeApp_autogen
.PHONY : GameOfLifeApp_autogen

# fast build rule for target.
GameOfLifeApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp_autogen.dir/build.make CMakeFiles/GameOfLifeApp_autogen.dir/build
.PHONY : GameOfLifeApp_autogen/fast

#=============================================================================
# Target rules for targets named GameOfLifeTests_autogen_timestamp_deps

# Build rule for target.
GameOfLifeTests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeTests_autogen_timestamp_deps
.PHONY : GameOfLifeTests_autogen_timestamp_deps

# fast build rule for target.
GameOfLifeTests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests_autogen_timestamp_deps.dir/build.make CMakeFiles/GameOfLifeTests_autogen_timestamp_deps.dir/build
.PHONY : GameOfLifeTests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named GameOfLifeTests_autogen

# Build rule for target.
GameOfLifeTests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLifeTests_autogen
.PHONY : GameOfLifeTests_autogen

# fast build rule for target.
GameOfLifeTests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests_autogen.dir/build.make CMakeFiles/GameOfLifeTests_autogen.dir/build
.PHONY : GameOfLifeTests_autogen/fast

#=============================================================================
# Target rules for targets named VLifeBenchmark_autogen_timestamp_deps

# Build rule for target.
VLifeBenchmark_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VLifeBenchmark_autogen_timestamp_deps
.PHONY : VLifeBenchmark_autogen_timestamp_deps

# fast build rule for target.
VLifeBenchmark_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark_autogen_timestamp_deps.dir/build.make CMakeFiles/VLifeBenchmark_autogen_timestamp_deps.dir/build
.PHONY : VLifeBenchmark_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named VLifeBenchmark_autogen

# Build rule for target.
VLifeBenchmark_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VLifeBenchmark_autogen
.PHONY : VLifeBenchmark_autogen

# fast build rule for target.
VLifeBenchmark_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark_autogen.dir/build.make CMakeFiles/VLifeBenchmark_autogen.dir/build
.PHONY : VLifeBenchmark_autogen/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock_autogen_timestamp_deps

# Build rule for target.
gmock_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_autogen_timestamp_deps
.PHONY : gmock_autogen_timestamp_deps

# fast build rule for target.
gmock_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen_timestamp_deps.dir/build
.PHONY : gmock_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gmock_autogen

# Build rule for target.
gmock_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_autogen
.PHONY : gmock_autogen

# fast build rule for target.
gmock_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen.dir/build
.PHONY : gmock_autogen/fast

#=============================================================================
# Target rules for targets named gmock_main_autogen_timestamp_deps

# Build rule for target.
gmock_main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main_autogen_timestamp_deps
.PHONY : gmock_main_autogen_timestamp_deps

# fast build rule for target.
gmock_main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen_timestamp_deps.dir/build
.PHONY : gmock_main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gmock_main_autogen

# Build rule for target.
gmock_main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main_autogen
.PHONY : gmock_main_autogen

# fast build rule for target.
gmock_main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen.dir/build
.PHONY : gmock_main_autogen/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest_autogen_timestamp_deps

# Build rule for target.
gtest_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_autogen_timestamp_deps
.PHONY : gtest_autogen_timestamp_deps

# fast build rule for target.
gtest_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_autogen_timestamp_deps.dir/build
.PHONY : gtest_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gtest_autogen

# Build rule for target.
gtest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_autogen
.PHONY : gtest_autogen

# fast build rule for target.
gtest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_autogen.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_autogen.dir/build
.PHONY : gtest_autogen/fast

#=============================================================================
# Target rules for targets named gtest_main_autogen_timestamp_deps

# Build rule for target.
gtest_main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main_autogen_timestamp_deps
.PHONY : gtest_main_autogen_timestamp_deps

# fast build rule for target.
gtest_main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen_timestamp_deps.dir/build
.PHONY : gtest_main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gtest_main_autogen

# Build rule for target.
gtest_main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main_autogen
.PHONY : gtest_main_autogen

# fast build rule for target.
gtest_main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen.dir/build
.PHONY : gtest_main_autogen/fast

GameOfLifeApp_autogen/mocs_compilation.o: GameOfLifeApp_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLifeApp_autogen/mocs_compilation.o

# target to build an object file
GameOfLifeApp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/GameOfLifeApp_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLifeApp_autogen/mocs_compilation.cpp.o

GameOfLifeApp_autogen/mocs_compilation.i: GameOfLifeApp_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLifeApp_autogen/mocs_compilation.i

# target to preprocess a source file
GameOfLifeApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/GameOfLifeApp_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLifeApp_autogen/mocs_compilation.cpp.i

GameOfLifeApp_autogen/mocs_compilation.s: GameOfLifeApp_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLifeApp_autogen/mocs_compilation.s

# target to generate assembly for a file
GameOfLifeApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/GameOfLifeApp_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLifeApp_autogen/mocs_compilation.cpp.s

GameOfLifeLib_autogen/mocs_compilation.o: GameOfLifeLib_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLifeLib_autogen/mocs_compilation.o

# target to build an object file
GameOfLifeLib_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/GameOfLifeLib_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLifeLib_autogen/mocs_compilation.cpp.o

GameOfLifeLib_autogen/mocs_compilation.i: GameOfLifeLib_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLifeLib_autogen/mocs_compilation.i

# target to preprocess a source file
GameOfLifeLib_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/GameOfLifeLib_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLifeLib_autogen/mocs_compilation.cpp.i

GameOfLifeLib_autogen/mocs_compilation.s: GameOfLifeLib_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLifeLib_autogen/mocs_compilation.s

# target to generate assembly for a file
GameOfLifeLib_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/GameOfLifeLib_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLifeLib_autogen/mocs_compilation.cpp.s

GameOfLifeTests_autogen/mocs_compilation.o: GameOfLifeTests_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLifeTests_autogen/mocs_compilation.o

# target to build an object file
GameOfLifeTests_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/GameOfLifeTests_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLifeTests_autogen/mocs_compilation.cpp.o

GameOfLifeTests_autogen/mocs_compilation.i: GameOfLifeTests_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLifeTests_autogen/mocs_compilation.i

# target to preprocess a source file
GameOfLifeTests_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/GameOfLifeTests_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLifeTests_autogen/mocs_compilation.cpp.i

GameOfLifeTests_autogen/mocs_compilation.s: GameOfLifeTests_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLifeTests_autogen/mocs_compilation.s

# target to generate assembly for a file
GameOfLifeTests_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/GameOfLifeTests_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLifeTests_autogen/mocs_compilation.cpp.s

VLifeBenchmark_autogen/mocs_compilation.o: VLifeBenchmark_autogen/mocs_compilation.cpp.o
.PHONY : VLifeBenchmark_autogen/mocs_compilation.o

# target to build an object file
VLifeBenchmark_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/VLifeBenchmark_autogen/mocs_compilation.cpp.o
.PHONY : VLifeBenchmark_autogen/mocs_compilation.cpp.o

VLifeBenchmark_autogen/mocs_compilation.i: VLifeBenchmark_autogen/mocs_compilation.cpp.i
.PHONY : VLifeBenchmark_autogen/mocs_compilation.i

# target to preprocess a source file
VLifeBenchmark_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/VLifeBenchmark_autogen/mocs_compilation.cpp.i
.PHONY : VLifeBenchmark_autogen/mocs_compilation.cpp.i

VLifeBenchmark_autogen/mocs_compilation.s: VLifeBenchmark_autogen/mocs_compilation.cpp.s
.PHONY : VLifeBenchmark_autogen/mocs_compilation.s

# target to generate assembly for a file
VLifeBenchmark_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/VLifeBenchmark_autogen/mocs_compilation.cpp.s
.PHONY : VLifeBenchmark_autogen/mocs_compilation.cpp.s

src/GameOfLifeView.o: src/GameOfLifeView.cpp.o
.PHONY : src/GameOfLifeView.o

# target to build an object file
src/GameOfLifeView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/src/GameOfLifeView.cpp.o
.PHONY : src/GameOfLifeView.cpp.o

src/GameOfLifeView.i: src/GameOfLifeView.cpp.i
.PHONY : src/GameOfLifeView.i

# target to preprocess a source file
src/GameOfLifeView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/src/GameOfLifeView.cpp.i
.PHONY : src/GameOfLifeView.cpp.i

src/GameOfLifeView.s: src/GameOfLifeView.cpp.s
.PHONY : src/GameOfLifeView.s

# target to generate assembly for a file
src/GameOfLifeView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/src/GameOfLifeView.cpp.s
.PHONY : src/GameOfLifeView.cpp.s

src/SimpleGameOfLife.o: src/SimpleGameOfLife.cpp.o
.PHONY : src/SimpleGameOfLife.o

# target to build an object file
src/SimpleGameOfLife.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/SimpleGameOfLife.cpp.o
.PHONY : src/SimpleGameOfLife.cpp.o

src/SimpleGameOfLife.i: src/SimpleGameOfLife.cpp.i
.PHONY : src/SimpleGameOfLife.i

# target to preprocess a source file
src/SimpleGameOfLife.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/SimpleGameOfLife.cpp.i
.PHONY : src/SimpleGameOfLife.cpp.i

src/SimpleGameOfLife.s: src/SimpleGameOfLife.cpp.s
.PHONY : src/SimpleGameOfLife.s

# target to generate assembly for a file
src/SimpleGameOfLife.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/SimpleGameOfLife.cpp.s
.PHONY : src/SimpleGameOfLife.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeApp.dir/build.make CMakeFiles/GameOfLifeApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/vlife/Tile.o: src/vlife/Tile.cpp.o
.PHONY : src/vlife/Tile.o

# target to build an object file
src/vlife/Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/vlife/Tile.cpp.o
.PHONY : src/vlife/Tile.cpp.o

src/vlife/Tile.i: src/vlife/Tile.cpp.i
.PHONY : src/vlife/Tile.i

# target to preprocess a source file
src/vlife/Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/vlife/Tile.cpp.i
.PHONY : src/vlife/Tile.cpp.i

src/vlife/Tile.s: src/vlife/Tile.cpp.s
.PHONY : src/vlife/Tile.s

# target to generate assembly for a file
src/vlife/Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/vlife/Tile.cpp.s
.PHONY : src/vlife/Tile.cpp.s

src/vlife/VLife.o: src/vlife/VLife.cpp.o
.PHONY : src/vlife/VLife.o

# target to build an object file
src/vlife/VLife.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/vlife/VLife.cpp.o
.PHONY : src/vlife/VLife.cpp.o

src/vlife/VLife.i: src/vlife/VLife.cpp.i
.PHONY : src/vlife/VLife.i

# target to preprocess a source file
src/vlife/VLife.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/vlife/VLife.cpp.i
.PHONY : src/vlife/VLife.cpp.i

src/vlife/VLife.s: src/vlife/VLife.cpp.s
.PHONY : src/vlife/VLife.s

# target to generate assembly for a file
src/vlife/VLife.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeLib.dir/build.make CMakeFiles/GameOfLifeLib.dir/src/vlife/VLife.cpp.s
.PHONY : src/vlife/VLife.cpp.s

tests/benchmark/VLifeBenchmark.o: tests/benchmark/VLifeBenchmark.cpp.o
.PHONY : tests/benchmark/VLifeBenchmark.o

# target to build an object file
tests/benchmark/VLifeBenchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/tests/benchmark/VLifeBenchmark.cpp.o
.PHONY : tests/benchmark/VLifeBenchmark.cpp.o

tests/benchmark/VLifeBenchmark.i: tests/benchmark/VLifeBenchmark.cpp.i
.PHONY : tests/benchmark/VLifeBenchmark.i

# target to preprocess a source file
tests/benchmark/VLifeBenchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/tests/benchmark/VLifeBenchmark.cpp.i
.PHONY : tests/benchmark/VLifeBenchmark.cpp.i

tests/benchmark/VLifeBenchmark.s: tests/benchmark/VLifeBenchmark.cpp.s
.PHONY : tests/benchmark/VLifeBenchmark.s

# target to generate assembly for a file
tests/benchmark/VLifeBenchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VLifeBenchmark.dir/build.make CMakeFiles/VLifeBenchmark.dir/tests/benchmark/VLifeBenchmark.cpp.s
.PHONY : tests/benchmark/VLifeBenchmark.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/vlife/VLifeTest.o: tests/vlife/VLifeTest.cpp.o
.PHONY : tests/vlife/VLifeTest.o

# target to build an object file
tests/vlife/VLifeTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/tests/vlife/VLifeTest.cpp.o
.PHONY : tests/vlife/VLifeTest.cpp.o

tests/vlife/VLifeTest.i: tests/vlife/VLifeTest.cpp.i
.PHONY : tests/vlife/VLifeTest.i

# target to preprocess a source file
tests/vlife/VLifeTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/tests/vlife/VLifeTest.cpp.i
.PHONY : tests/vlife/VLifeTest.cpp.i

tests/vlife/VLifeTest.s: tests/vlife/VLifeTest.cpp.s
.PHONY : tests/vlife/VLifeTest.s

# target to generate assembly for a file
tests/vlife/VLifeTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLifeTests.dir/build.make CMakeFiles/GameOfLifeTests.dir/tests/vlife/VLifeTest.cpp.s
.PHONY : tests/vlife/VLifeTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... GameOfLifeApp_autogen"
	@echo "... GameOfLifeApp_autogen_timestamp_deps"
	@echo "... GameOfLifeLib_autogen"
	@echo "... GameOfLifeLib_autogen_timestamp_deps"
	@echo "... GameOfLifeTests_autogen"
	@echo "... GameOfLifeTests_autogen_timestamp_deps"
	@echo "... VLifeBenchmark_autogen"
	@echo "... VLifeBenchmark_autogen_timestamp_deps"
	@echo "... gmock_autogen"
	@echo "... gmock_autogen_timestamp_deps"
	@echo "... gmock_main_autogen"
	@echo "... gmock_main_autogen_timestamp_deps"
	@echo "... gtest_autogen"
	@echo "... gtest_autogen_timestamp_deps"
	@echo "... gtest_main_autogen"
	@echo "... gtest_main_autogen_timestamp_deps"
	@echo "... run_benchmark"
	@echo "... run_benchmark_quick"
	@echo "... run_tests"
	@echo "... GameOfLifeApp"
	@echo "... GameOfLifeLib"
	@echo "... GameOfLifeTests"
	@echo "... VLifeBenchmark"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... GameOfLifeApp_autogen/mocs_compilation.o"
	@echo "... GameOfLifeApp_autogen/mocs_compilation.i"
	@echo "... GameOfLifeApp_autogen/mocs_compilation.s"
	@echo "... GameOfLifeLib_autogen/mocs_compilation.o"
	@echo "... GameOfLifeLib_autogen/mocs_compilation.i"
	@echo "... GameOfLifeLib_autogen/mocs_compilation.s"
	@echo "... GameOfLifeTests_autogen/mocs_compilation.o"
	@echo "... GameOfLifeTests_autogen/mocs_compilation.i"
	@echo "... GameOfLifeTests_autogen/mocs_compilation.s"
	@echo "... VLifeBenchmark_autogen/mocs_compilation.o"
	@echo "... VLifeBenchmark_autogen/mocs_compilation.i"
	@echo "... VLifeBenchmark_autogen/mocs_compilation.s"
	@echo "... src/GameOfLifeView.o"
	@echo "... src/GameOfLifeView.i"
	@echo "... src/GameOfLifeView.s"
	@echo "... src/SimpleGameOfLife.o"
	@echo "... src/SimpleGameOfLife.i"
	@echo "... src/SimpleGameOfLife.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/vlife/Tile.o"
	@echo "... src/vlife/Tile.i"
	@echo "... src/vlife/Tile.s"
	@echo "... src/vlife/VLife.o"
	@echo "... src/vlife/VLife.i"
	@echo "... src/vlife/VLife.s"
	@echo "... tests/benchmark/VLifeBenchmark.o"
	@echo "... tests/benchmark/VLifeBenchmark.i"
	@echo "... tests/benchmark/VLifeBenchmark.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/vlife/VLifeTest.o"
	@echo "... tests/vlife/VLifeTest.i"
	@echo "... tests/vlife/VLifeTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

